Work in progress
well1791/trankilino pull request #4
Opened 2021-11-05 21:12 UTC by fabi1989

closes #2

2021-11-06 18:50 UTC, well1791 requested changes
@fabi1989 bastante bien! porfa atiende los comentarios

2021-11-06 18:50 UTC, well1791 commented on css/main.css
> +}
@fabi1989 mira como corregir ese "caracter de final de pagina"

2021-11-06 18:50 UTC, well1791 commented on css/main.css
> +.segundo-nav {
@fabi1989 `segundo-nav` no es un buen nombre de clase, renombralo a algo que tenga mas sentido, toma en cuenta que "segundo nav" realmente no es un segundo nav, sino un "espacio de fondo"

2021-11-06 18:50 UTC, well1791 commented on css/main.css
> +  background-color: #e5e5e5;
@fabi1989 usa variables de css para este color

2021-11-06 18:50 UTC, well1791 commented on css/main.css
> +  border: 2px solid #B6D1D1;
@fabi1989 usa una variable para el color

2021-11-06 18:50 UTC, well1791 commented on css/main.css
> +  top: 0px;
@fabi1989 no hace falta poner `0px`, en lugar de ello cambialo a `0`

2021-11-08 10:29 UTC, fabi1989 commented on css/main.css
> +  background-color: #e5e5e5;
listo

2021-11-08 10:30 UTC, fabi1989 commented on css/main.css
> +  top: 0px;
listo

2021-11-08 10:30 UTC, fabi1989 commented on css/main.css
> +.segundo-nav {
listongo

2021-11-08 10:31 UTC, fabi1989 commented on css/main.css
> +}
esta no entiendo..que caractér?

2021-11-08 15:48 UTC, well1791 requested changes

2021-11-08 15:48 UTC, well1791 commented on css/main.css
> +}
@fabi1989  no necesitas una linea para cada cosa.. puedes agrupar todo en el mismo `root`

```css
:root {
  --body-color: #e5e5e5;
  --bordernav-color: #b6d1d1;
  --color-logo:#0E607A;
  --sombra-logo:#6b77a2;
}
```

2021-11-08 15:48 UTC, well1791 commented on css/main.css
> +}
@fabi1989 ese icono rojo que ves despues del `}`, hazle _hover_ con el cursor, y lee lo que te dice: "No newline at end of file" (no linea nueva al final del archivo).

Por buenas practicas se acostumbra a dejar siempre un enter al final de cada archivo, para evitar ese "error" que ves ahi. Asegurate de cambiar los archivos que correspondan para que cumplan con ese criterio.

2021-11-08 15:48 UTC, well1791 commented on font/Apache License.txt
> +Apache License
@fabi1989 este archivo no corresponde a este PR

2021-11-08 15:48 UTC, well1791 commented on index.html
> +      <h1 class="logo">Myte Website</h1>
@fabi1989 este codigo no corresponde a este PR, quitalo

2021-11-08 15:48 UTC, well1791 commented on index.html
> +  <div class="hidden-space"></div>
@fabi1989  el nombre de clase es mejor, pero aun falta un detalle, "hidden-space" (espacio escondido) es muy generico, o sea, el nombre de clase sugiere que cualquier elemento de html podria ser usado para tener un "espacio escondido", lo mejor que puedes hacer es comprometer el nombre con la seccion/componente a quien pertenece.

```html
  <div class="header-hidden-space"></div>
```

o tambien

```html
  <div class="header-backdrop"></div>
```

"backdrop" significa "fondo"

2021-11-08 15:48 UTC, well1791 commented on css/main.css
> +}
@fabi1989 si vas a escribir las clases en ingles como "title" o "container", se consistente con todo el proyecto. Los nombres de las variables de css deberian estar en ingles tambien

2021-11-09 09:17 UTC, fabi1989 commented on css/main.css
> +}
listooo

2021-11-09 09:20 UTC, fabi1989 commented on css/main.css
> +}
listo!!!!, no sabia q se podia, ni habia probado :s

2021-11-09 09:24 UTC, fabi1989 commented on index.html
> +  <div class="hidden-space"></div>
listooo!!!!!, q locura que me salga aqui lo que deba corregir, facilita monton

2021-11-09 09:50 UTC, fabi1989 commented on index.html
> +      <h1 class="logo">Myte Website</h1>
mijo, no se que hice mijo.esto de cherry pick, esos mensajes q me salen en la consola ç:s jajaja,

2021-11-09 16:07 UTC, fabi1989 commented on css/main.css
> +  background-color: #e5e5e5;
yala

2021-11-09 16:15 UTC, well1791 requested changes

2021-11-09 16:15 UTC, well1791 commented on css/main.css
> +.segundo-nav {
@fabi1989 renombra esto a `header-backdrop`

2021-11-09 16:15 UTC, well1791 commented on index.html
> +</html>
@fabi1989 corrige el caracter de fin de archivo

2021-11-09 16:15 UTC, well1791 commented on css/main.css
> +  --color-nav-border:#b6d1d1;
@fabi1989 deja un espacio luego del `:`

```css
  --color-body: #e5e5e5;
  --color-nav-border: #b6d1d1;
```

2021-11-09 16:17 UTC, fabi1989 commented on css/main.css
> +  --color-nav-border:#b6d1d1;
listo ahi

2021-11-09 16:19 UTC, fabi1989 commented on index.html
> +</html>
listou

2021-11-09 16:19 UTC, fabi1989 commented on css/main.css
> +.segundo-nav {
lestou

2021-11-09 16:20 UTC, well1791 commented on css/main.css
> +
@fabi1989 espacio innecesario =/

2021-11-09 16:21 UTC, well1791 requested changes

2021-11-09 16:21 UTC, well1791 commented on index.html
> +</html>
@fabi1989 sigo viendo ese caracter, debes dar un enter debajo del tag

```html
</body>
</html>



```

2021-11-09 16:40 UTC, well1791 approved these changes

2021-11-09 16:41 UTC, merged

2021-11-10 09:49 UTC, fabi1989 commented
ahi, hice pullrequest