Nav logo
well1791/trankilino pull request #8
Opened 2021-11-09 15:34 UTC by fabi1989

closes #5

2021-11-10 13:46 UTC, well1791 requested changes

2021-11-10 13:46 UTC, well1791 commented on css/main.css
> +@font-face {
@fabi1989 todo lo que sea fonts agregalos en otro archivo css `fonts.css` para no tener un solo archivo gigante con todo dentro

2021-11-10 13:46 UTC, well1791 commented on git status
> +[33mcommit a3b81c7f6d635521268c3bb5edf5e514813e718c[m[33m ([m[1;36mHEAD -> [m[1;32mheader-container[m[33m, [m[1;31morigin/header-container[m[33m)[m
@fabi1989 este archivo no tiene sentido, borralo

2021-11-11 04:03 UTC, fabi1989 commented on css/main.css
> +@font-face {
Listo,archivo Fonts, creado.... xD

2021-11-11 04:24 UTC, well1791 requested changes

2021-11-11 04:24 UTC, well1791 commented on index.html
> +  <link rel="stylesheet" href="css/fonts.css">
@fabi1989 el orden debe ser, `fonts` primero, luego `main`

2021-11-11 04:30 UTC, fabi1989 commented on index.html
> +  <link rel="stylesheet" href="css/fonts.css">
listonsh

2021-11-11 06:45 UTC, well1791 requested changes

2021-11-11 06:45 UTC, well1791 commented on font/Apache License.txt
> +Apache License
@fabi1989 borra este archivo

2021-11-11 23:11 UTC, well1791 requested changes

2021-11-12 15:41 UTC, fabi1989 commented on css/main.css
> +  line-height: 41,2px ;
yata!

2021-11-12 15:43 UTC, fabi1989 commented on css/main.css
> +  text-decoration: none;
listeylor

2021-11-12 15:56 UTC, well1791 requested changes

2021-11-12 15:56 UTC, well1791 commented on css/main.css
> +.header-tittle {
@fabi1989 cambia el nombre de la clase, este seria realmente el contenedor del logo, no el titulo del header.. usualmente las paginas webs usan imagenes para mostrar el logo de la pagina

```css
.logo-container {
```

2021-11-12 16:01 UTC, fabi1989 commented on css/main.css
> +.header-tittle {
yalamijo

2021-11-12 16:03 UTC, well1791 approved these changes

2021-11-12 16:09 UTC, merged