Nueva rama
well1791/trankilino pull request #9
Opened 2021-11-10 10:07 UTC by fabi1989

well...porfa me confirmas, si esta todo correcto ya con la nueva rama, y con el  ultimo commit q subi a nueva rama, espero ya tener terminado ese capitulo po! pilas me cuentas <3 te amodoro

2021-11-10 12:56 UTC, well1791 commented
closes #2

2021-11-10 13:43 UTC, well1791 requested changes

2021-11-10 13:43 UTC, well1791 commented on css/main.css
> +  --header-height: 52px;
@fabi1989 creo que es mejor si movemos todas las variables a un solo archivo.. create un archivo `variables.css` y en ese escribe todas las variables

2021-11-11 04:14 UTC, fabi1989 commented on css/main.css
> +  --header-height: 52px;
listongo!!!!

2021-11-11 04:22 UTC, well1791 requested changes

2021-11-11 04:22 UTC, well1791 commented on css/variables.css
> +}
@fabi1989 falta el espacio debajo

2021-11-11 04:22 UTC, well1791 commented on index.html
> +  <link rel="stylesheet" href="css/variables.css">
@fabi1989 esta linea debe ir primero

```diff
+  <link rel="stylesheet" href="css/variables.css">
   <link rel="stylesheet" href="css/main.css">
```

2021-11-11 04:24 UTC, fabi1989 commented on css/variables.css
> +}
listo, subido commit!!!

2021-11-11 04:48 UTC, well1791 approved these changes
@fabi1989 buen trabajo! ✅

2021-11-11 04:48 UTC, merged

2021-11-11 04:48 UTC, fabi1989 commented
al fin!!!!!!!!!!